site_name: PIISA
theme:
  name: material

nav:
  - Home: index.md
  - Libraries: libraries.md
  - Proposals: proposals.md
  - Specifications: specs.md
  - Usage: usage.md
  
extra: 
  social: 
  - icon: fontawesome/brands/github 
    link: https://github.com/piisa/piisa
