site_name: PIISA
theme:
  name: material

nav:
  - Home: index.md
  - PII Data Specification: specs.md
  - Usage: usage.md
  - Libraries: libraries.md
  - Configuration: configuration.md
  
extra: 
  social: 
  - icon: fontawesome/brands/github 
    link: https://github.com/piisa/piisa
    name: GitHub
  - icon: simple/substack
    link: https://privacyprotection.substack.com/
    name: Substack