site_name: PIISA
theme:
  name: material

nav:
  - Home: index.md
  - Specification: specs.md
  - Usage: usage.md
  - Libraries: libraries.md
  - Configuration: configuration.md
  
extra: 
  social: 
  - icon: fontawesome/brands/github 
    link: https://github.com/piisa/piisa
